# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bjm/physic_sim/try_im

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bjm/physic_sim/try_im

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bjm/physic_sim/try_im/CMakeFiles /home/bjm/physic_sim/try_im//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bjm/physic_sim/try_im/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_opengl

# Build rule for target.
my_opengl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_opengl
.PHONY : my_opengl

# fast build rule for target.
my_opengl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/build
.PHONY : my_opengl/fast

#=============================================================================
# Target rules for targets named my_drawer

# Build rule for target.
my_drawer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_drawer
.PHONY : my_drawer

# fast build rule for target.
my_drawer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/build
.PHONY : my_drawer/fast

canvas.o: canvas.cpp.o
.PHONY : canvas.o

# target to build an object file
canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/canvas.cpp.o
.PHONY : canvas.cpp.o

canvas.i: canvas.cpp.i
.PHONY : canvas.i

# target to preprocess a source file
canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/canvas.cpp.i
.PHONY : canvas.cpp.i

canvas.s: canvas.cpp.s
.PHONY : canvas.s

# target to generate assembly for a file
canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/canvas.cpp.s
.PHONY : canvas.cpp.s

drawer.o: drawer.cpp.o
.PHONY : drawer.o

# target to build an object file
drawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/drawer.cpp.o
.PHONY : drawer.cpp.o

drawer.i: drawer.cpp.i
.PHONY : drawer.i

# target to preprocess a source file
drawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/drawer.cpp.i
.PHONY : drawer.cpp.i

drawer.s: drawer.cpp.s
.PHONY : drawer.s

# target to generate assembly for a file
drawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/drawer.cpp.s
.PHONY : drawer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/main.cpp.s
.PHONY : main.cpp.s

small_imgui/imgui.o: small_imgui/imgui.cpp.o
.PHONY : small_imgui/imgui.o

# target to build an object file
small_imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui.cpp.o
.PHONY : small_imgui/imgui.cpp.o

small_imgui/imgui.i: small_imgui/imgui.cpp.i
.PHONY : small_imgui/imgui.i

# target to preprocess a source file
small_imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui.cpp.i
.PHONY : small_imgui/imgui.cpp.i

small_imgui/imgui.s: small_imgui/imgui.cpp.s
.PHONY : small_imgui/imgui.s

# target to generate assembly for a file
small_imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui.cpp.s
.PHONY : small_imgui/imgui.cpp.s

small_imgui/imgui_demo.o: small_imgui/imgui_demo.cpp.o
.PHONY : small_imgui/imgui_demo.o

# target to build an object file
small_imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_demo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_demo.cpp.o
.PHONY : small_imgui/imgui_demo.cpp.o

small_imgui/imgui_demo.i: small_imgui/imgui_demo.cpp.i
.PHONY : small_imgui/imgui_demo.i

# target to preprocess a source file
small_imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_demo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_demo.cpp.i
.PHONY : small_imgui/imgui_demo.cpp.i

small_imgui/imgui_demo.s: small_imgui/imgui_demo.cpp.s
.PHONY : small_imgui/imgui_demo.s

# target to generate assembly for a file
small_imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_demo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_demo.cpp.s
.PHONY : small_imgui/imgui_demo.cpp.s

small_imgui/imgui_draw.o: small_imgui/imgui_draw.cpp.o
.PHONY : small_imgui/imgui_draw.o

# target to build an object file
small_imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_draw.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_draw.cpp.o
.PHONY : small_imgui/imgui_draw.cpp.o

small_imgui/imgui_draw.i: small_imgui/imgui_draw.cpp.i
.PHONY : small_imgui/imgui_draw.i

# target to preprocess a source file
small_imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_draw.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_draw.cpp.i
.PHONY : small_imgui/imgui_draw.cpp.i

small_imgui/imgui_draw.s: small_imgui/imgui_draw.cpp.s
.PHONY : small_imgui/imgui_draw.s

# target to generate assembly for a file
small_imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_draw.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_draw.cpp.s
.PHONY : small_imgui/imgui_draw.cpp.s

small_imgui/imgui_impl_glfw.o: small_imgui/imgui_impl_glfw.cpp.o
.PHONY : small_imgui/imgui_impl_glfw.o

# target to build an object file
small_imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_glfw.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_glfw.cpp.o
.PHONY : small_imgui/imgui_impl_glfw.cpp.o

small_imgui/imgui_impl_glfw.i: small_imgui/imgui_impl_glfw.cpp.i
.PHONY : small_imgui/imgui_impl_glfw.i

# target to preprocess a source file
small_imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_glfw.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_glfw.cpp.i
.PHONY : small_imgui/imgui_impl_glfw.cpp.i

small_imgui/imgui_impl_glfw.s: small_imgui/imgui_impl_glfw.cpp.s
.PHONY : small_imgui/imgui_impl_glfw.s

# target to generate assembly for a file
small_imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_glfw.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_glfw.cpp.s
.PHONY : small_imgui/imgui_impl_glfw.cpp.s

small_imgui/imgui_impl_opengl3.o: small_imgui/imgui_impl_opengl3.cpp.o
.PHONY : small_imgui/imgui_impl_opengl3.o

# target to build an object file
small_imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_opengl3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_opengl3.cpp.o
.PHONY : small_imgui/imgui_impl_opengl3.cpp.o

small_imgui/imgui_impl_opengl3.i: small_imgui/imgui_impl_opengl3.cpp.i
.PHONY : small_imgui/imgui_impl_opengl3.i

# target to preprocess a source file
small_imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_opengl3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_opengl3.cpp.i
.PHONY : small_imgui/imgui_impl_opengl3.cpp.i

small_imgui/imgui_impl_opengl3.s: small_imgui/imgui_impl_opengl3.cpp.s
.PHONY : small_imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
small_imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_impl_opengl3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_impl_opengl3.cpp.s
.PHONY : small_imgui/imgui_impl_opengl3.cpp.s

small_imgui/imgui_tables.o: small_imgui/imgui_tables.cpp.o
.PHONY : small_imgui/imgui_tables.o

# target to build an object file
small_imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_tables.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_tables.cpp.o
.PHONY : small_imgui/imgui_tables.cpp.o

small_imgui/imgui_tables.i: small_imgui/imgui_tables.cpp.i
.PHONY : small_imgui/imgui_tables.i

# target to preprocess a source file
small_imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_tables.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_tables.cpp.i
.PHONY : small_imgui/imgui_tables.cpp.i

small_imgui/imgui_tables.s: small_imgui/imgui_tables.cpp.s
.PHONY : small_imgui/imgui_tables.s

# target to generate assembly for a file
small_imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_tables.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_tables.cpp.s
.PHONY : small_imgui/imgui_tables.cpp.s

small_imgui/imgui_widgets.o: small_imgui/imgui_widgets.cpp.o
.PHONY : small_imgui/imgui_widgets.o

# target to build an object file
small_imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_widgets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_widgets.cpp.o
.PHONY : small_imgui/imgui_widgets.cpp.o

small_imgui/imgui_widgets.i: small_imgui/imgui_widgets.cpp.i
.PHONY : small_imgui/imgui_widgets.i

# target to preprocess a source file
small_imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_widgets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_widgets.cpp.i
.PHONY : small_imgui/imgui_widgets.cpp.i

small_imgui/imgui_widgets.s: small_imgui/imgui_widgets.cpp.s
.PHONY : small_imgui/imgui_widgets.s

# target to generate assembly for a file
small_imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_opengl.dir/build.make CMakeFiles/my_opengl.dir/small_imgui/imgui_widgets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_drawer.dir/build.make CMakeFiles/my_drawer.dir/small_imgui/imgui_widgets.cpp.s
.PHONY : small_imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_drawer"
	@echo "... my_opengl"
	@echo "... canvas.o"
	@echo "... canvas.i"
	@echo "... canvas.s"
	@echo "... drawer.o"
	@echo "... drawer.i"
	@echo "... drawer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... small_imgui/imgui.o"
	@echo "... small_imgui/imgui.i"
	@echo "... small_imgui/imgui.s"
	@echo "... small_imgui/imgui_demo.o"
	@echo "... small_imgui/imgui_demo.i"
	@echo "... small_imgui/imgui_demo.s"
	@echo "... small_imgui/imgui_draw.o"
	@echo "... small_imgui/imgui_draw.i"
	@echo "... small_imgui/imgui_draw.s"
	@echo "... small_imgui/imgui_impl_glfw.o"
	@echo "... small_imgui/imgui_impl_glfw.i"
	@echo "... small_imgui/imgui_impl_glfw.s"
	@echo "... small_imgui/imgui_impl_opengl3.o"
	@echo "... small_imgui/imgui_impl_opengl3.i"
	@echo "... small_imgui/imgui_impl_opengl3.s"
	@echo "... small_imgui/imgui_tables.o"
	@echo "... small_imgui/imgui_tables.i"
	@echo "... small_imgui/imgui_tables.s"
	@echo "... small_imgui/imgui_widgets.o"
	@echo "... small_imgui/imgui_widgets.i"
	@echo "... small_imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

